# Numpy Exercise

 # Create a 1D NumPy array of numbers from 0 to 9

In [11]:
import numpy as np
ar = np.arange(10)
print(ar)

[0 1 2 3 4 5 6 7 8 9]


# Convert 1D array to 2D

In [17]:
ar = np.arange(6)
arr = ar.reshape(2,3)
print(arr)

[[0 1 2]
 [3 4 5]]


# Print Array Attributes

Instructions: Print the following attributes of the array:

The shape of the array.

The number of array dimensions.

The size of each element in bytes.

In [26]:
my_array = np.array([[1, 2], [3, 4], [5, 6], [7, 8]], dtype=np.uint16)
print('The shape of the array is:', my_array.shape)

The shape of the array is: (4, 2)


In [28]:
print('The number of dimensions is:', my_array.ndim)

The number of dimensions is: 2


In [30]:
print('The size of each element in bytes is:', my_array.itemsize)

The size of each element in bytes is: 2


# Create a 3×3 NumPy array of all True

In [37]:
data = np.array([[True, True, True],[True, True, True],[True, True, True]])
print(data)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [39]:
data = np.ones((3,3), dtype=bool)
print(data)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


# Extract the documentation of NumPy’s arange() function

In [46]:
np.info(np.arange)

arange([start,] stop[, step,], dtype=None, *, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.  The interval includes 

# Create a 1D array filled with zeros and another filled with ones

In [53]:
Zee = np.zeros(5)
dee = np.ones(5)
print('Zeros:', Zee)
print('Ones:', dee)

Zeros: [0. 0. 0. 0. 0.]
Ones: [1. 1. 1. 1. 1.]


# Create a 1D array of 10 evenly spaced values between 5 and 50

In [62]:
ar = np.linspace(5, 50, 10)
print(ar)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


# Convert a Python list into a NumPy array

In [67]:
py_list = [1, 2, 3, 4, 5]
py_array = np.array(py_list)
print(py_array)

[1 2 3 4 5]


 # Find the memory size of a NumPy array of numbers from 0 to 9

In [80]:
data = np.arange(10)
print('Array:',data)
print('Memory size in bytes:', data.nbytes)

Array: [0 1 2 3 4 5 6 7 8 9]
Memory size in bytes: 40


# Reverse a 1D NumPy array

In [85]:
arr = np.arange(10)
reversed1 = arr[::-1]
print(reversed1)

[9 8 7 6 5 4 3 2 1 0]


#  Create a 3×3 identity matrix

In [105]:
data = np.eye(3, 3)
print(data)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Create a 4×4 array and extract its first row and last column

In [124]:
data = np.arange(1, 17).reshape(4,4)
print('Array:\n',data)
print('First Row:', data[0])
print('Last column:', data[:,-1])

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
First Row: [1 2 3 4]
Last column: [ 4  8 12 16]


#  Extract Odd Rows and Even Columns

In [8]:
import numpy as np
sampleArray = np.array([
    [3, 6, 9, 12], 
    [15, 18, 21, 24], 
    [27, 30, 33, 36], 
    [39, 42, 45, 48], 
    [51, 54, 57, 60]
])
new = sampleArray[1::2, ::2]
print('New array with odd rows and even columns:\n', new)

New array with odd rows and even columns:
 [[15 21]
 [39 45]]


# Stack arrays horizontally

In [13]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.hstack((a,b))
print(c)

[1 2 3 4 5 6]


# Slice the first two rows and first two columns from a 4×4 array

In [28]:
data = np.arange(1, 17).reshape(4,4)
print('Array:\n',data)
new = data[0:2, 0:2]
print('First 2 rows and columns:\n',new)

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
First 2 rows and columns:
 [[1 2]
 [5 6]]


# Replace all odd numbers in a NumPy array with -1

In [36]:
data = np.arange(1,11)
print('original:',data)
data[data % 2 == 1] = -1
print('new:', data)

original: [ 1  2  3  4  5  6  7  8  9 10]
new: [-1  2 -1  4 -1  6 -1  8 -1 10]


# Get the indices of non-zero elements in an array

In [43]:
data = np.array([1, 0, 2, 0, 3, 0, 4])
print('Array:',data)
data2 = np.nonzero(data)
print('Indices:', data2)

Array: [1 0 2 0 3 0 4]
Indices: (array([0, 2, 4, 6], dtype=int64),)


# Find the common items between two arrays

In [46]:
a = np.array([1, 2, 3, 2, 8, 4, 2, 4])
b = np.array([2, 4, 5, 6, 8])
c = np.intersect1d(a,b)
print(c)

[2 4 8]


# Perform arithmetic operations on two NumPy arrays element-wise

Add two NumPy arrays element by element.

Multiply two NumPy arrays element by element.

In [58]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.add(a,b) # or c = a + b
print('Sum:', c)

Sum: [5 7 9]


In [56]:
d= np.multiply(a,b) # or d = a * b
print('multiplication:', d)

multiplication: [ 4 10 18]


# Matrix multiplication
Write a code to compute the dot product of two NumPy arrays

In [63]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.dot(a,b) # or a @ b
print('dot product:', c)

dot product: 32


# Compute the mean, median, and standard deviation of a NumPy array

In [70]:
arr = np.array([10, 20, 30, 100, 200, 300])
print('mean:', np.mean(arr))
print('median:', np.median(arr))
print('standard deviation:', np.std(arr))

mean: 110.0
median: 65.0
standard deviation: 107.08252269472673


# Remove common items from array

The np.in1d() function checks if each element of the first array is also present in the second array, returning a boolean array.

The ~ operator is the bitwise NOT operator, which inverts the boolean mask (e.g., True becomes False). We use this inverted mask to select only the elements from a that are not present in b.

In [86]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 6, 7, 8, 9])
c = np.in1d(a,b)
d = a[~c]
print(c)
print(d)

[False False False False  True]
[1 2 3 4]


# Normalize a NumPy array (values between 0 and 1)

(arr - arr.min()) / (arr.max() - arr.min()) :

Subtract the minimum value so the smallest becomes 0.
Divide by the range (max - min) so the largest becomes 1.
This scales all values into [0, 1].

In [91]:
arr = np.array([10, 20, 30, 40, 50])
new = (arr - arr.min()) / (arr.max() - arr.min())
print(new)

[0.   0.25 0.5  0.75 1.  ]


#  Get the positions where elements of array a and b match

In [95]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 4, 3, 7, 8])
c = np.where(a == b)
print(c)

(array([0, 2], dtype=int64),)


# Extract numbers from an array

Write a code to extract all numbers from an array that are between 5 and 10 (inclusive).

In [99]:
data = np.arange(20)
data2 = data[(data >= 5) & (data <= 10)]
print(data2)

[ 5  6  7  8  9 10]
